name: Sync
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false 
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/TBXark/ChatGPT-Telegram-Workers.git"
        target_repo: "https://github.com/taocwang/ChatGPT-Telegram-Workers.git"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.PAT }}
       
